SkillsFundingAgency/dfc-shared-appgateway

- Resources/ArmTemplates/app-gateway.json
- Resources/template.json
- Resources/test-parameters.json
Split out the public IP address creation so you can use the separate template to do this
> NCSD-870: Public IP

- Resources/template.json
> NCSD-881: Override backend protocol to https

- Resources/template.json
The customProbeProperties parameter is incorrect in parameters.json
> NCSD-931: parameter fix

- Resources/parameters.json
Tokenized the rewrite rules in parameters.json
> NCSD-929: Tokenized rules

- Resources/ArmTemplates/app-gateway.json
- Resources/ArmTemplates/app-gateway.md
- Resources/parameters.json
- Resources/template.json
- Resources/test-parameters.json
Allows multiple http settings to be specified and routing rules specify which one they want
> NCSD-909: Multiple http settings

- Resources/ArmTemplates/app-gateway.json
- Resources/ArmTemplates/app-gateway.md
- Resources/parameters.json
- Resources/template.json
- Resources/test-parameters.json
Enables private IP address for app gateway
> NCSD-967: Private IP address

- Resources/parameters.json
Added capacity param to paramters.json
> NCSD-1300: Added param for instances

- Resources/parameters.json
Fix: param for instances should be int not a string
> NCSD-1300: param fix

- Resources/ArmTemplates/app-gateway.json
- Resources/ArmTemplates/app-gateway.md
- Resources/parameters.json
- Resources/template.json
Enable diagnostic (logging) on app gateway if a storage account or OMS workspace ID provided
> NCSD-1289 logging

- Resources/parameters.json
Changed the BAU backend settings to use an IP address and configured rewrite rule for location
> NCSD-1363: Changed BAU settings

- Resources/ArmTemplates/app-gateway.json
- Resources/parameters.json
Setting of hostname on back end pool
> NCSD-1363: Backend settings

- Resources/parameters.json
Added location rewrite rule for SHC to skills-assessment/SHC
> Added location rewrite rule for SHC and removed about-us

- Resources/parameters.json
Added session timeout error page and email changed alert page to the BAU backend pool.
> Added the missing alerts for direct domain

- Resources/ArmTemplates/app-gateway.json
- Resources/ArmTemplates/app-gateway.md
Optional timeout can be added to http settings object to set the requestTimeout
> NCSD-1383: Allow setting of timeout

- Resources/parameters.json
Updated parameters file for DFC-10294 to allow /home/signin to BAU backend pool
> Update parameters.json as fix for DFC-10294

- Resources/template.json
Removed Capacity alert until Microsoft fix the issue (see case 119082822001046)
> NCSD-1474: Removed Capacity alert

- Resources/parameters.json
Added start new SHC exclusion to AG
> Adding start new SHC exclusion to AG

- Resources/template.json
Allow creation of App Gateway with WAF functionality
> NCSD-1664: WAF AG

- Resources/AzureDevOps/azure-pipelines.yml
Build on check-in or PR to dev or master branches
> NCSD-1675: Gitflow YAML build

- Resources/parameters.json
Added new backend pool for composite app service with corresponding rewrite rule for location
> NCSD-1676: Composite backend pool

- Resources/ArmTemplates/app-gateway.json
- Resources/ArmTemplates/app-gateway.md
- Resources/template.json
Create optional array to set custom error pages. Will update parameters file when they are ready to deploy a custom page.
> NCSD-1384: Custom error pages

- Resources/parameters.json
So that it can be tested side by side
> Updated compui to use /app as path override

- Resources/parameters.json
Help path to Composite UI app service
> NCSD-1678: Help path

- Resources/parameters.json
- Added route for JP default to composite backend pool
- Added route /sf/* to force route to service frontend in sitefinity (e.g. /sf/job-profiles/gp)
> DFC-11385 JP comp ui routing

- Resources/template.json
Adding the capacity metric alert back in
> NCSD-1417: Capacity alert

- Resources/parameters.json
Added DYSAC route under CUI as direct path, as well as under Skills Assessment sub route
> DYSAC route

- Resources/parameters.json
- Added path for DYSAC
- Added path for help
- Added path for alerts
> Release v1.1.33.1

- Resources/parameters.json
Added /matchskills/* path to comp UI
> NCSD-3058 matchskills

- Resources/parameters.json
> Patching syntax error

- Resources/parameters.json
- Comp UI path routing fix when it is app specific home page 
- matchskills route
> Release v1.1.36.1

- Resources/parameters.json
Added "your-account" path to "comp ui" backend pool
> Added "your-account" path to comp ui backend pool 

- Resources/AzureDevOps/azure-pipelines.yml
- Resources/parameters.json
Remove "help" path as this is not planned to be supported through content pages anymore for v1 CUI release.
> Removed "help" path from CUI

- Resources/AzureDevOps/azure-pipelines.yml
- Resources/parameters.json
Removed the following
- help
- dysac
- mstc
Configured for CUI
- Job profiles
- alerts
All others are default route to sitefintiy.
> Update to CUI v1 release requirement

- Resources/parameters.json
1. As per NCSD-4340 added Contact-us Under CompUI paths
2. As per NCSD-4313 added Find-a-course and skills toolkit under CompUI paths
3. As per NCSD-4359 Created new health probe for composite UI , created new CompUIHTTPSSettings and configured Probe and routing accordingly.
> Updated Health Address for Composite UI and Created New CompUI Probe

- Resources/parameters.json
- Change health address from /home to /health/ping for CompUi
- Create new Health Probe
- added support for skills toolkit in Comp Ui Paths
> added new health probe and skills toolkit in compui paths

- Resources/parameters.json
Removed following from comp-ui paths as they no longer required.
auth
action-plans
your-account
Added 
Contact-us
webchat
> NCSD-3345 Add contact us and Webchat

- Resources/parameters.json
Configured new path under Compui backend
/api/Ajax/Action
> NCSD-4857-Added new path under Compui for api ajax

- Resources/parameters.json
Configured
Find-a-course
api/Ajax
> NCSD-4889 CompUIFAC-Newpath

- Resources/parameters.json
Added support for Account and action plans under CUI paths
> NCSD-5075 added support AAP CUi

- Resources/parameters.json
This PR includes
1. Changed default backend to shell from sitefinity 
2. Removed path based routing for shell
3. Introduced path based routing for sitefinity
> NCSD-5436 Make CUI as Default Backend

- Resources/parameters.json
This PR includes New path under CUI routing for careers advice.
> NCSD-5452 New path under CUI for careers advice

- Resources/parameters.json
Added two new rules JobProfileRewrite1 and JobProfileRewrite2
> Added two new rules to app gateway

- Resources/parameters.json
Reverts SkillsFundingAgency/dfc-shared-appgateway#107
> Revert "Ncslt 773 agw url redirect rule to remove special characters"

- Resources/parameters.json
Removed robots.txt from appGateway rules
> Removed robots.txt from rules

- Resources/parameters.json
* Update parameters.json
Removed routing Rules:     "/jp-feedback-thankyou" and "/jp-feedback-thankyou/*"
* Update parameters.json
remove esfa/welcome redirection from AGW
* Removed robots.txt from rules
Co-authored-by: Raph-zek <97975567+Raph-zek@users.noreply.github.com>
Co-authored-by: mhdkurdi <105785411+mhdkurdi@users.noreply.github.com>
Co-authored-by: thomas-petty-dfe <thomas.petty@education.gov.uk>
> Merge Release 21 into master
